name: first

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
              - name: Set current date as env variable
                run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
              - name: Echo current date
                run: echo $NOW # Gives "2022-12-11T01:42:20"
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
              - name: Set current date as env variable
                run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
              - name: Echo current date
                run: echo $NOW # Gives "2022-12-11T01:42:20"
    job3:
        name: Third Job
        runs-on: windows-latest
        steps:
              - name: Set current date as env variable
                run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
              - name: Echo current date
                run: echo $NOW # Gives "2022-12-11T01:42:20"
    job4:
        name: Fourth Job
        needs: [job1, job2, job3]
        runs-on: windows-latest
        steps:
              - name: Set current date as env variable
                run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
              - name: Echo current date
                run: echo $NOW # Gives "2022-12-11T01:42:20"
